(()=>{'use strict';
const qs=(s,r=document)=>r.querySelector(s),all=(s,r=document)=>[...r.querySelectorAll(s)];
const menu=qs('#mobile-menu'),toggle=qs('.menu-toggle');
function closeMenu(){menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');toggle.textContent='☰'}
toggle?.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');toggle.textContent=open?'×':'☰'});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){closeMenu();toggle.focus()}});
document.addEventListener('click',e=>{if(!menu.hidden&&!menu.contains(e.target)&&!toggle.contains(e.target))closeMenu()});
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const progress=qs('.reading-progress'),orbit=qs('.hero-orbit');let ticking=false;
function onScroll(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{const height=document.documentElement.scrollHeight-innerHeight;progress.style.width=(height>0?scrollY/height*100:0)+'%';if(orbit&&!reduce.matches)orbit.style.setProperty('--scroll',Math.min(scrollY/innerHeight,1));ticking=false})}
addEventListener('scroll',onScroll,{passive:true});onScroll();
qs('.back-top')?.addEventListener('click',()=>scrollTo({top:0,behavior:reduce.matches?'instant':'smooth'}));
if('IntersectionObserver'in window&&!reduce.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.04});all('.section-header,.product-card,.cap-infra-row,.usp-card,.intro-pillar-card').forEach(n=>{n.classList.add('reveal-ready');observer.observe(n)})}
const track=qs('.product-slider-track'),dots=all('.slider-dot');
if(track){const step=()=>track.firstElementChild.getBoundingClientRect().width+25;const go=i=>track.scrollTo({left:i*step(),behavior:reduce.matches?'instant':'smooth'});qs('.slider-btn-next')?.addEventListener('click',()=>{const end=track.scrollWidth-track.clientWidth;go(track.scrollLeft>=end-5?0:Math.round(track.scrollLeft/step())+1)});qs('.slider-btn-prev')?.addEventListener('click',()=>go(Math.max(0,Math.round(track.scrollLeft/step())-1)));dots.forEach((d,i)=>d.addEventListener('click',()=>go(i)));track.addEventListener('scroll',()=>{let active=Math.round(track.scrollLeft/step());dots.forEach((d,i)=>{d.classList.toggle('active',i===active);d.setAttribute('aria-pressed',String(i===active))})},{passive:true});}
const params=new URLSearchParams(location.search);
const specs=qs('#specsModal');
if(specs){all('[data-open-specs]').forEach(b=>b.addEventListener('click',()=>specs.showModal()));all('[data-close-specs]').forEach(b=>b.addEventListener('click',()=>specs.close()));specs.addEventListener('click',e=>{if(e.target===specs){const r=specs.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)specs.close()}});qs('[data-print-specs]')?.addEventListener('click',()=>window.print())}
all('.quote-form').forEach(form=>{
 const product=params.get('product');const select=qs('[name="product_type"]',form);
 if(product&&select){const matching=[...select.options].find(o=>o.text.toLowerCase()===product.toLowerCase());if(matching)select.value=matching.value;else{let o=new Option(product,product,true,true);select.add(o)}}
 if(params.get('action')==='audit')qs('[name="message"]',form).value='I would like to schedule a facility audit.';
 const labels={contact_name:'Full name',company_name:'Company',email:'Business email',phone:'Phone',country:'Country',product_type:'Product',estimated_quantity:'Estimated quantity',requirement:'Packaging requirement',specifications:'Technical specifications',message:'Message'};
 function body(){const data=new FormData(form);return 'PHARMACEUTICAL PACKAGING ENQUIRY\nPrince Art Packages\n\n'+Object.entries(labels).map(([k,v])=>v+': '+(data.get(k)||'Not specified')).join('\n\n')}
 form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const subject='Packaging quotation — '+qs('[name="company_name"]',form).value;location.href='mailto:sales@princeartpackages.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body());qs('.form-status',form).textContent='Your enquiry is prepared. Send it from your email application and attach any artwork there. If your email application did not open, download the enquiry and email it to sales@princeartpackages.com. Nothing has been sent automatically.'});
 qs('[data-download-rfq]',form)?.addEventListener('click',()=>{if(!form.reportValidity())return;const u=URL.createObjectURL(new Blob([body()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='prince-art-packaging-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);qs('.form-status',form).textContent='Your enquiry has been downloaded. Email it with your artwork to sales@princeartpackages.com. It has not been sent yet.'});
});
// Repair legacy product anchors while preserving incoming links.
const aliases={'product-folding-cartons':'product-printed-cartons','product-leaf-inserts':'product-leaf-inserts','product-printed-labels':'product-printed-labels','product-temper-evident':'product-temper-evident','quote-form':'enquiry-form'};
if(location.hash){const id=decodeURIComponent(location.hash.slice(1));if(!document.getElementById(id)&&aliases[id])document.getElementById(aliases[id])?.scrollIntoView()}
const context=document.modelContext,quote=qs('.quote-form');
if(context?.registerTool&&quote){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const fields=['contact_name','company_name','email','phone','country','product_type','estimated_quantity','requirement','specifications','message'];try{Promise.resolve(context.registerTool({name:'stage_packaging_enquiry',title:'Prepare packaging enquiry fields',description:'Fill the visible packaging enquiry form for review. Does not send email, submit a request, upload files, or download anything.',inputSchema:{type:'object',properties:Object.fromEntries(fields.map(k=>[k,{type:'string',maxLength:4000}])),additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected enquiry fields');for(const[k,v]of Object.entries(input)){if(!fields.includes(k)||typeof v!=='string'||v.length>4000)throw new Error('Invalid enquiry field');if(k==='product_type'&&![...quote.elements.product_type.options].some(o=>o.value===v))throw new Error('Choose an available product type')}for(const[k,v]of Object.entries(input))quote.elements[k].value=v;qs('.form-status',quote).textContent='Enquiry fields prepared for your review. Nothing has been sent.';return{status:'staged',sent:false,fieldsUpdated:Object.keys(input)}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
})();
